apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: helloworld-deployment1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: hamed-labels
        image: hhaddadian/hamed-node-minikube-kops
        ports:
        - name: nodejs-port
          containerPort: 3000
      nodeSelector:
        hardware: high-spec
