apiVersion: v1
kind: Pod
metadata:
  name: hamed-node.minikube.com
  labels:
    app: hamed-node-app
spec:
  containers:
  - name: hamednodejsminikube-container
    image: hhaddadian/hamed-node-minikube-kops
    ports:
    - containerPort: 3000
