apiVersion: v1
kind: Pod
metadata:
  name: helloworld-nginx1
  labels:
    app: helloworld-nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.11
    ports:
    - name: nginxport
      containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d
  - name: hamedsecondcontainer
    image: hhaddadian/nodejs
    ports:
    - name: nodejsport
      containerPort: 3000
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
        items:
        - key: reversproxy.conf
          path: reverseproxy.conf
