apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: hamed-deployment
        image: hhaddadian/hamed-node-minikube-kops
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: credvolume
          mountPath: /etc/creds
          readOnly: true
      volumes:
      - name: credvolume
        secret:
          secretName: db-secret
