apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.laodbalancer.com
  labels:
    app: helloworld
spec:
  containers:
  - name: hamednodejs
    image: hhaddadian/nodejs
    ports:
    - name: nodejs-port
      containerPort: 3000
