apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: hamednodejs
    image: hhaddadian/nodejs
    ports:
    - containerPort: 3000
